const taskForm=document.getElementById('taskForm');
const taskInput=document.getElementById('taskInput');
const reminderInput=document.getElementById('reminderInput');
const taskList=document.getElementById('taskList');
const taskStats=document.getElementById('taskStats');
const clearCompletedBtn=document.getElementById('clearCompletedBtn');
const filterAllBtn=document.getElementById('filterAllBtn');
const filterActiveBtn=document.getElementById('filterActiveBtn');
const filterCompletedBtn=document.getElementById('filterCompletedBtn');
const enablePushBtn=document.getElementById('enablePushBtn');
const disablePushBtn=document.getElementById('disablePushBtn');
const networkStatus=document.getElementById('networkStatus');
const STORAGE_KEY='practice_13_14_todos_v2';
const VAPID_PUBLIC_KEY='BBvh44fl9I5XDzI6F26gRCgeLLf0NW0PX-SNG0CNd2bSP3jNydtSqgGTvcNCuD_fZgB_xRF7Ocy8x-v97LPU-fU';
let socket=null;
function loadTasks(){try{const raw=localStorage.getItem(STORAGE_KEY);const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[]}catch(e){console.error('Не удалось прочитать задачи из localStorage:',e);return[]}}
function saveTasks(tasks){localStorage.setItem(STORAGE_KEY,JSON.stringify(tasks))}
function generateId(){return`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function formatReminderDate(value){if(!value){return''}const date=new Date(Number(value));if(Number.isNaN(date.getTime())){return''}return new Intl.DateTimeFormat('ru-RU',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(date)}
async function scheduleTaskReminder(task){if(!task?.reminder){return}const reminderTime=Number(task.reminder);if(Number.isNaN(reminderTime)){return}try{await fetch('/schedule-reminder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:task.id,text:task.text,reminder:reminderTime})})}catch(error){console.warn('Не удалось отправить напоминание на сервер:',error)}}
function scheduleAllPendingReminders(){if(!navigator.onLine){return}const tasks=loadTasks();tasks.forEach((task)=>{if(task.reminder&&!task.completed){scheduleTaskReminder(task)}})}
function updateNetworkStatus(){const isOnline=navigator.onLine;networkStatus.textContent=isOnline?'Онлайн':'Офлайн';networkStatus.classList.toggle('badge--success',isOnline);networkStatus.classList.toggle('badge--offline',!isOnline)}
function createTaskElement(task){const li=document.createElement('li');li.className='task-item';li.dataset.id=task.id;const left=document.createElement('div');left.className='task-item__left';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=task.completed;checkbox.dataset.action='toggle';checkbox.setAttribute('aria-label','Отметить задачу выполненной');const text=document.createElement('span');text.className='task-item__text';text.textContent=task.text;if(task.completed){text.classList.add('task-item__text--completed')}left.appendChild(checkbox);left.appendChild(text);if(task.reminder){const reminderInfo=document.createElement('div');reminderInfo.className='task-item__reminder';reminderInfo.textContent=`Напоминание: ${formatReminderDate(task.reminder)}`;left.appendChild(reminderInfo)}const actions=document.createElement('div');actions.className='task-item__actions';const editBtn=document.createElement('button');editBtn.type='button';editBtn.className='button button--secondary button--small';editBtn.textContent='Редактировать';editBtn.dataset.action='edit';const deleteBtn=document.createElement('button');deleteBtn.type='button';deleteBtn.className='button button--danger button--small';deleteBtn.textContent='Удалить';deleteBtn.dataset.action='delete';actions.appendChild(editBtn);actions.appendChild(deleteBtn);li.appendChild(left);li.appendChild(actions);return li}
function updateStats(tasks){const total=tasks.length;const completed=tasks.filter((task)=>task.completed).length;const active=total-completed;taskStats.textContent=`Всего: ${total} | Активных: ${active} | Выполненных: ${completed}`}
let currentFilter='all'
function filterTasks(tasks){if(currentFilter==='active'){return tasks.filter((task)=>!task.completed)}if(currentFilter==='completed'){return tasks.filter((task)=>task.completed)}return tasks}
function updateFilterButtons(){const buttons=[filterAllBtn,filterActiveBtn,filterCompletedBtn];buttons.forEach((button)=>{if(!button)return;button.classList.toggle('filter-button--active',button.dataset.filter===currentFilter)})}
function renderTasks(){const tasks=loadTasks();const visible=filterTasks(tasks);taskList.innerHTML='';if(visible.length===0){const empty=document.createElement('li');empty.className='empty-state';empty.textContent=tasks.length===0?'Пока задач нет. Добавьте первую запись.':currentFilter==='completed'?'Нет выполненных задач для показа.':currentFilter==='active'?'Нет активных задач для показа.':'Нет задач для показа.';taskList.appendChild(empty);updateStats(tasks);updateFilterButtons();return}visible.forEach((task)=>{taskList.appendChild(createTaskElement(task))});updateStats(tasks);updateFilterButtons()}
function editTask(taskId,newText){const normalized=newText.trim();if(!normalized){return}const updated=loadTasks().map((task)=>task.id===taskId?{...task,text:normalized}:task);saveTasks(updated);renderTasks()}
function addTask(text){const normalizedText=text.trim();let reminderTimestamp=null;if(!normalizedText){return}if(reminderInput&&reminderInput.value){const parsed=new Date(reminderInput.value).getTime();reminderTimestamp=Number.isNaN(parsed)?null:parsed}const tasks=loadTasks();const newTask={id:generateId(),text:normalizedText,completed:false,createdAt:new Date().toISOString(),reminder:reminderTimestamp};tasks.unshift(newTask);saveTasks(tasks);renderTasks();if(socket&&socket.connected){socket.emit('newTask',newTask)}scheduleTaskReminder(newTask)}
function handleTaskListClick(event){const action=event.target.dataset.action;const taskId=event.target.closest('li')?.dataset.id;if(!action||!taskId){return}if(action==='toggle'){toggleTask(taskId);return}if(action==='delete'){deleteTask(taskId);return}if(action==='edit'){const tasks=loadTasks();const task=tasks.find((item)=>item.id===taskId);if(!task){return}const newText=window.prompt('Измените текст задачи:',task.text);if(newText===null){return}editTask(taskId,newText)}}
function toggleTask(taskId){const updated=loadTasks().map((task)=>task.id===taskId?{...task,completed:!task.completed}:task);saveTasks(updated);renderTasks()}
function deleteTask(taskId){const confirmed=window.confirm('Вы точно хотите удалить эту задачу?');if(!confirmed){return}const updated=loadTasks().filter((task)=>task.id!==taskId);saveTasks(updated);renderTasks()}
function clearCompletedTasks(){const completed=loadTasks().filter((task)=>task.completed);if(completed.length===0){return}const confirmed=window.confirm('Удалить все отмеченные как выполненные задачи?');if(!confirmed){return}const updated=loadTasks().filter((task)=>!task.completed);saveTasks(updated);renderTasks()}
function urlBase64ToUint8Array(base64String){const padding='='.repeat((4-(base64String.length%4))%4);const base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/');const rawData=window.atob(base64);const outputArray=new Uint8Array(rawData.length);for(let i=0;i<rawData.length;++i){outputArray[i]=rawData.charCodeAt(i)}return outputArray}
async function subscribeToPush(){if(!('serviceWorker' in navigator)||!('PushManager' in window)){alert('Push-уведомления не поддерживаются этим браузером.');return}try{const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(VAPID_PUBLIC_KEY)});await fetch('/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscription})});await updatePushButtons();alert('Вы успешно подписаны на уведомления.')}catch(error){console.error('Ошибка подписки на push:',error);alert('Не удалось подписаться на уведомления.')}}
async function unsubscribeFromPush(){if(!('serviceWorker' in navigator)||!('PushManager' in window)){alert('Push-уведомления не поддерживаются этим браузером.');return}try{const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.getSubscription();if(!subscription){await updatePushButtons();return}await fetch('/unsubscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscription})});await subscription.unsubscribe();await updatePushButtons();alert('Уведомления отключены.')}catch(error){console.error('Ошибка отписки от push:',error);alert('Не удалось отключить уведомления.')}}
async function updatePushButtons(){if(!('serviceWorker' in navigator)||!('PushManager' in window)){if(enablePushBtn)enablePushBtn.disabled=true;if(disablePushBtn)disablePushBtn.disabled=true;return}const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.getSubscription();const subscribed=Boolean(subscription);if(enablePushBtn){enablePushBtn.disabled=subscribed}if(disablePushBtn){disablePushBtn.disabled=!subscribed}}
async function initPushSubscriptionState(){if(!('serviceWorker' in navigator)||!('PushManager' in window)){if(enablePushBtn)enablePushBtn.disabled=true;if(disablePushBtn)disablePushBtn.disabled=true;return}try{await navigator.serviceWorker.ready;await updatePushButtons()}catch(error){console.error('Не удалось получить состояние push-подписки:',error)}}
function createSocketConnection(){if(!window.io){return}socket=io();socket.on('connect',()=>{});socket.on('taskAdded',(task)=>{alert(`Новое событие: добавлена задача «${task.text}».`)})}
function registerServiceWorker(){if(!('serviceWorker' in navigator)){return}window.addEventListener('load',async()=>{try{await navigator.serviceWorker.register('./sw.js');await initPushSubscriptionState();createSocketConnection()}catch(error){console.error('Ошибка регистрации Service Worker:',error)}})}
function setupEventListeners(){taskForm.addEventListener('submit',(event)=>{event.preventDefault();addTask(taskInput.value);taskForm.reset();taskInput.focus()});taskList.addEventListener('click',handleTaskListClick);taskList.addEventListener('change',(event)=>{const target=event.target;if(target.dataset.action!=='toggle'){return}const taskItem=target.closest('.task-item');if(!taskItem){return}toggleTask(taskItem.dataset.id)});if(clearCompletedBtn){clearCompletedBtn.addEventListener('click',clearCompletedTasks)}if(filterAllBtn){filterAllBtn.dataset.filter='all';filterAllBtn.addEventListener('click',()=>{currentFilter='all';renderTasks()})}if(filterActiveBtn){filterActiveBtn.dataset.filter='active';filterActiveBtn.addEventListener('click',()=>{currentFilter='active';renderTasks()})}if(filterCompletedBtn){filterCompletedBtn.dataset.filter='completed';filterCompletedBtn.addEventListener('click',()=>{currentFilter='completed';renderTasks()})}if(enablePushBtn){enablePushBtn.addEventListener('click',subscribeToPush)}if(disablePushBtn){disablePushBtn.addEventListener('click',unsubscribeFromPush)}window.addEventListener('online',()=>{updateNetworkStatus();scheduleAllPendingReminders()});window.addEventListener('offline',updateNetworkStatus)}
async function init(){setupEventListeners();updateNetworkStatus();renderTasks();scheduleAllPendingReminders();registerServiceWorker()}
init()
