const CACHE_NAME='practice-13-14-cache-v5';
const RUNTIME_CACHE_NAME='practice-13-14-runtime-cache-v2';
const FALLBACK_HTML='./offline.html';
const ASSETS_TO_CACHE=['./','./index.html','./about.html','./styles.css','./manifest.json','./offline.html','./assets/hero.png','./assets/icons/favicon.ico','./assets/icons/favicon-16x16.png','./assets/icons/favicon-32x32.png','./assets/icons/favicon-48x48.png','./assets/icons/favicon-64x64.png','./assets/icons/favicon-128x128.png','./assets/icons/favicon-256x256.png','./assets/icons/favicon-512x512.png','./assets/icons/apple-touch-icon-57x57.png','./assets/icons/apple-touch-icon-114x114.png','./assets/icons/apple-touch-icon-120x120.png','./assets/icons/apple-touch-icon.png'];
self.addEventListener('install',(event)=>{event.waitUntil(caches.open(CACHE_NAME).then((cache)=>cache.addAll(ASSETS_TO_CACHE)));self.skipWaiting()});
self.addEventListener('activate',(event)=>{event.waitUntil(caches.keys().then((cacheKeys)=>Promise.all(cacheKeys.filter((key)=>key!==CACHE_NAME).map((oldKey)=>caches.delete(oldKey)))));self.clients.claim()});
self.addEventListener('push',(event)=>{const payload=event.data?.json()||{title:'PlanDo',body:'Новое уведомление от приложения.'};const title=payload.title||'PlanDo';const options={body:payload.body||'У вас новое уведомление.',icon:'./assets/icons/favicon-128x128.png',badge:'./assets/icons/favicon-48x48.png',data:payload.data||{},actions:[{action:'snooze',title:'Отложить на 5 минут'}]};event.waitUntil(self.registration.showNotification(title,options))});
self.addEventListener('notificationclick',(event)=>{event.notification.close();if(event.action==='snooze'){event.waitUntil((async()=>{try{const {taskId}=event.notification.data||{};if(taskId){await fetch('/postpone-reminder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({taskId})});await self.registration.showNotification('Напоминание отложено',{body:'Мы перенесли уведомление на 5 минут.',icon:'./assets/icons/favicon-128x128.png',badge:'./assets/icons/favicon-48x48.png'})}}catch(error){console.error('Не удалось отложить напоминание:',error)}})());return}event.waitUntil(self.clients.openWindow('./'))});
self.addEventListener('fetch',(event)=>{if(event.request.method!=='GET'){return}const requestUrl=new URL(event.request.url);if(requestUrl.pathname.startsWith('/socket.io')){return}if(event.request.mode==='navigate'){event.respondWith(networkFirst(event.request));return}if(requestUrl.origin===self.location.origin&&['style','script','image','font'].includes(event.request.destination)){event.respondWith(cacheFirst(event.request));return}event.respondWith(cacheFirst(event.request))});
async function networkFirst(request){try{const response=await fetch(request);if(response&&response.status===200){const cache=await caches.open(RUNTIME_CACHE_NAME);cache.put(request,response.clone())}return response}catch(error){const cachedResponse=await caches.match(request);return cachedResponse||caches.match(FALLBACK_HTML)}}
async function cacheFirst(request){const cachedResponse=await caches.match(request);if(cachedResponse){return cachedResponse}try{const response=await fetch(request);const cache=await caches.open(RUNTIME_CACHE_NAME);cache.put(request,response.clone());return response}catch(error){return Response.error()}}
